# CONFIG
# VERSION INFO: 0.1-7.18

# CHANGE SERVER SETTINGS HERE
# ALL OF THESE VALUES *MUST* BE SET --> LIMITED ERROR HANDLING
# IN ORDER FOR CHANGES TO TAKE EFFECT, THE SERVER MUST BE RESTARTED 


REBOOT_TIME = 1                     # TIME IN SECONDS TO WAIT INBETWEEN SHUTDOWN OR REBOOT STEPS (DEPENDING ON SERVER LAG AND USER COUNT YOU MIGHT WANT TO INCREMENT THIS VALUE)
LOCAL_ADDRESS = ""                  # LOCAL IPv4 ADDRESS OF HOSTING MACHINE (I.E. 192.168.X.X or 10.X.X.X)
LOCAL_PORT = 0                      # LOCAL PORT FOR THE HOSTING MACHINE TO LISTEN ON
SUPPORT_EMAIL_HOST = ""             # DOMAIN NAME OF SMTP SERVICE (I.E. smtp.gmail.com)
SUPPORT_EMAIL_SSL_PORT = 0          # SSL ENABLED PORT OF SMTP SERVICE
SUPPORT_EMAIL_ADDRESS = ""          # YOUR EMAIL ADDRESS
SUPPORT_EMAIL_PASSWORD = ""         # YOUR EMAIL PASSWORD
