import ssl
# CONFIG
# SERVER SETTINGS
REBOOT_TIME = 1
LOCAL_ADDRESS = "X.X.X.X"
LOCAL_PORT = 4447
USE_PERSISTENT_RSA_KEYS = True
CERTIFICATES_ENABLED = True
CERTIFICATES_ALLOW_PASSPHRASE_ARGUMENT_ON_REBOOT = False

# SQL SETTINGS
TABLE_USER_LENGTH = 16
TABLE_CLIENTLOG_LENGTH = 6
TABLE_BLACKLIST_LENGTH = 4
TABLE_CONNECTUSERCOOKIES_LENGTH = 2
TABLE_COOKIES_LENGTH = 5
TABLE_DATA_LENGTH = 11
TABLE_SERVERLOG_LENGTH = 4
TABLE_DELETE_LENGTH = 3
TABLE_BLOCKEDCOOKIES_LENGTH = 4
# 2FA SETTINGS
ACCOUNT_ACTIVATION_MAX_TIME = 3600
DELETE_ACCOUNT_CONFIRMATION_MAX_TIME = 1800
MAX_CODE_ATTEMPTS = 3
MAX_CODE_ATTEMPTS_ADMIN = 3
NEW_DEVICE_CONFIRMATION_MAX_TIME = 1800
NEW_DEVICE_CONFIRMATION_ADMIN_MAX_TIME = 1800
RESEND_CODE_MAX_COUNT = 3
PASSWORD_CHANGE_CONFIRMATION_MAX_TIME = 1800
PASSWORD_CHANGE_CONFIRMATION_ADMIN_MAX_TIME = 1800
WRONG_CODE_AUTOBAN_DURATION = 3600
WRONG_CODE_AUTOBAN_DURATION_ADMIN = 86400
# EMAIL SETTINGS
# VALID SUPPORT_EMAIL_SSL_PROTOCOL_VERSIONS ARE:
# 	ssl.PROTOCOL_SSLv23   
#	ssl.PROTOCOL_TLS        
#	ssl.PROTOCOL_TLSv1       
#	ssl.PROTOCOL_TLSv1_1
#	ssl.PROTOCOL_TLSv1_2
SUPPORT_EMAIL_SSL_PROTOCOL_VERSION = ssl.PROTOCOL_TLSv1_2
SUPPORT_EMAIL_HOST = ""
SUPPORT_EMAIL_SSL_PORT = 587
SUPPORT_EMAIL_ADDRESS = ""
SUPPORT_EMAIL_PASSWORD = ""
SUPPORT_EMAIL_LOGO = "icon.png"
SUPPORT_EMAIL_SENDER = "PMDBS Support"
# VERSION INFO
PYTHON_VERSIONS = ["3.6.6", "3.6.7", "3.6.8rc1", "3.7.2+", "3.7.3rc1", "3.7.3"]
CONFIG_VERSION = "0.7-2b.19"
CONFIG_BUILD = "development"
